spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
  
  sql:
      init:
        mode: always
        schema-locations: classpath:schema-h2.sql
  
  jpa:
     hibernate:
        ddl-auto: none
        
  batch:
      jdbc:
        initialize-schema: always
  
